### ISSUE TITLE
Does this plugin support multiple profilers?

### ISSUE THREAD

**Issue by srangwal** [melix/jmh-gradle-plugin#72]
(NOTE: I am using 0.3.0) 

From the docs it looks like it does. So when I use
```
profilers = [' org.openjdk.jmh.profile.GCProfiler ', ' org.openjdk.jmh.profile.StackProfiler ']
```

I get 
```
java.lang.ClassNotFoundException:  org.openjdk.jmh.profile.GCProfiler -prof org.openjdk.jmh.profile.StackProfiler 
Profilers failed to initialize, exiting.
```

Looking at this code in JMHPluginExtension.java 
```java
   private void addOption(List<String> options, List values, String option, String separator) {
        if (values!=null) {
            options.add("-"+option);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < values.size(); i++) {
                final Object value = values.get(i);
                sb.append(value);
                if (i<values.size()-1) {
                    sb.append(separator);
                }
            }
            options.add(sb.toString());
        }
    }
```

should options.add() be called for each value in the List? In addition, a space is required in the first option, (after every separator as well or should the separator include the space?) and after every value i.e., 
```java
options.add("-" + option + " ");
.....
....
sb.append(value + " ");
```

**Comment by vyazelenko** [comment]
@srangwal The list of supported profilers to be specified is the same as you get when passing `-lprof` key to JMH. Here is the output I get on my Mac OS X:
```
Supported profilers:
                  cl: Classloader profiling via standard MBeans 
                comp: JIT compiler profiling via standard MBeans 
                  gc: GC profiling via standard MBeans 
               hs_cl: HotSpot (tm) classloader profiling via implementation-specific MBeans 
             hs_comp: HotSpot (tm) JIT compiler profiling via implementation-specific MBeans 
               hs_gc: HotSpot (tm) memory manager (GC) profiling via implementation-specific MBeans 
               hs_rt: HotSpot (tm) runtime profiling via implementation-specific MBeans 
              hs_thr: HotSpot (tm) threading subsystem via implementation-specific MBeans 
               stack: Simple and naive Java stack profiler 

Unsupported profilers:
                perf: <none> 
[Cannot run program "perf": error=2, No such file or directory]
             perfasm: <none> 
[Cannot run program "perf": error=2, No such file or directory]
            perfnorm: <none> 
[Cannot run program "perf": error=2, No such file or directory]
            xperfasm: <none> 
[Cannot run program "xperf": error=2, No such file or directory]
```
Anyway PR #74 will update documentation and list all supported profilers.

**Comment by aalmiray** [comment]
Fixed with #74

**Comment by srangwal** [comment]
My (maybe flawed) guess is that the issue is with the way the options are combined. When I use ``` profilers = ['gc']```everything works fine but when I use ```  profilers = ['gc', 'stack']``` I get the error 

```
java.lang.ClassNotFoundException: gc-profstack
```

**Comment by aalmiray** [comment]
Fixed with https://github.com/melix/jmh-gradle-plugin/commit/da68800d0171975244c427bacbc1c445c88781c6

**Comment by srangwal** [comment]
I can emulated the behaviour of the fix above with 
```
  profilers = [' gc ', ' stack ']
```
notice the space before and after each profiler name

But I still get the error 
```
java.lang.ClassNotFoundException:  gc -prof stack 
```
